; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-11-18 at 19:17:10
; total layer number: 1
; filament_density: 1.02,1.02,1.02,1.24,1.24,1.24
; filament_diameter: 1.75,1.75,1.75,1.75,1.75,1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 50x50 372
; iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAA3klEQVR4Ae2ZoQ4CQQxE+yVoHMlaDA
; qLJBjMaSyaP+PToEcg2WBIrrPsbDPPnLrNdbp5aXpmQgghRGtWtrOrPWxrNxuevd1fxZz8ORc2NGvv
; yMWLSdOd6V1Miu7MV+3THapiln5M3Z3uFL/vkWSpRBBNlkoEiGRpRIBIthZB9+4gkqURASJZKk0jRD
; AxiSCaLI2mEckWaboRBazp4UVQnyERoIkmq3mtFZrXfpzRFc1rX9CJINW8lkoEB0CyR39/w7AopEoW
; AdVuLArt5nIpNJMwgnS/MM5ejBBCCPEHnnKA4bNLmIGwAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.62mm
; perimeters extrusion width = 0.62mm
; infill extrusion width = 0.62mm
; solid infill extrusion width = 0.62mm
; top infill extrusion width = 0.62mm
; first layer extrusion width = 0.62mm

; external perimeters extrusion width = 0.62mm
; perimeters extrusion width = 0.62mm
; infill extrusion width = 0.62mm
; solid infill extrusion width = 0.62mm
; top infill extrusion width = 0.62mm
; first layer extrusion width = 0.62mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=137.2,135 POLYGON=[[136.9,125],[137.5,125],[137.5,145],[136.9,145],[136.9,125]]
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_1_copy_0 CENTER=132.8,135 POLYGON=[[132.5,125],[133.1,125],[133.1,145],[132.5,145],[132.5,125]]
M73 P0 R0
M106 S0
M106 P2 S0
;TYPE:Custom
PRINT_START BED=100 HOTEND=260 CHAMBER=60 EXTRUDER=0
SET_PRINT_STATS_INFO TOTAL_LAYER=1
M83
M140 S100
M104 S260
M141 S60
G4 P3000
T0
G1 X108.000 Y1 F30000
G0 Z0.2 F600
M73 P2 R0
;G1 E3 F1800
G90
M83
G0 X128 E8  F1320
G0 X133 E.3742  F2200
M73 P5 R0
G0 X138 E.3742  F8800
M73 P6 R0
G0 X143 E.3742  F2200
G0 X148 E.3742  F8800
G0 X153 E.3742  F2200
G91
G1 X1 Z-0.300
M73 P7 R0
G1 X4
G1 Z1 F1200
M73 P8 R0
G90
M400
G1 X108.000 Y2.5 F30000
G0 Z0.2 F600
M73 P9 R0
M83
G0 X128 E10  F1320
G0 X133 E.3742  F2200
M73 P13 R0
G0 X138 E.3742  F8800
G0 X143 E.3742  F2200
G0 X148 E.3742  F8800
M73 P14 R0
G0 X153 E.3742  F2200
G91
G1 X1 Z-0.300
M73 P15 R0
G1 X4
G1 Z1 F1200
G90
M400
G1 Z1 F600
M73 P16 R0
M106 P3 S255
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
SET_PRESSURE_ADVANCE ADVANCE=0.015; Override pressure advance value
T0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

 ; timelapse without wipe tower
TIMELAPSE_TAKE_FRAME

G92 E0
SET_PRINT_STATS_INFO CURRENT_LAYER=1
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
G1 E-.8 F1800
G1 X127.799 Y124.202 F30000
G1 Z.6
M73 P19 R0
G1 Z.2
G1 E.8 F1800
M73 P20 R0
;TYPE:Skirt
;WIDTH:0.62
G1 F3000
G1 X128.03 Y123.078 E.05067
G1 X129.154 Y121.468 E.08665
G1 X130.821 Y120.433 E.08665
G1 X132.5 Y120.134 E.07527
G1 X137.5 Y120.134 E.22073
G1 X139.422 Y120.53 E.08665
M73 P21 R0
G1 X141.032 Y121.654 E.08665
G1 X142.067 Y123.321 E.08665
G1 X142.366 Y125 E.07527
G1 X142.366 Y145 E.88291
M73 P22 R0
G1 X141.97 Y146.922 E.08665
M73 P23 R0
G1 X140.846 Y148.532 E.08665
G1 X139.179 Y149.567 E.08665
G1 X137.5 Y149.866 E.07527
M73 P24 R0
G1 X132.5 Y149.866 E.22073
G1 X130.578 Y149.47 E.08665
G1 X128.968 Y148.346 E.08665
G1 X127.933 Y146.679 E.08665
M73 P25 R0
G1 X127.634 Y145 E.07527
G1 X127.634 Y125 E.88291
G1 X127.787 Y124.26 E.03333
M73 P27 R0
G1 X128.347 Y124.384 F30000
G1 F3000
G1 X128.607 Y123.202 E.05343
G1 X129.72 Y121.735 E.08129
G1 X131.346 Y120.87 E.08129
G1 X132.5 Y120.711 E.05144
G1 X137.5 Y120.711 E.22073
M73 P28 R0
G1 X139.298 Y121.107 E.08129
G1 X140.765 Y122.22 E.08129
G1 X141.63 Y123.846 E.08129
G1 X141.789 Y125 E.05144
M73 P29 R0
G1 X141.789 Y145 E.88291
G1 X141.393 Y146.798 E.08129
M73 P30 R0
G1 X140.28 Y148.265 E.08129
G1 X138.654 Y149.13 E.08129
M73 P31 R0
G1 X137.5 Y149.289 E.05144
G1 X132.5 Y149.289 E.22073
G1 X130.702 Y148.893 E.08129
G1 X129.235 Y147.78 E.08129
G1 X128.37 Y146.154 E.08129
M73 P32 R0
G1 X128.211 Y145 E.05144
G1 X128.211 Y125 E.88291
G1 X128.334 Y124.442 E.02521
M73 P34 R0
; printing object Cube id:0 copy 0
G1 E-.8 F1800
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 X131.394 Y131.434 Z.6 F30000
G1 X137.2 Y144.7 Z.6
G1 Z.2
M73 P36 R0
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.599998
G1 F3000
G1 X137.2 Y125.3 E.82674
; stop printing object Cube id:0 copy 0
; printing object Cube id:1 copy 0
G1 E-.8 F1800
M73 P38 R0
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
EXCLUDE_OBJECT_START NAME=Cube_id_1_copy_0
G1 X135.512 Y132.743 Z.6 F30000
G1 X132.8 Y144.7 Z.6
G1 Z.2
M73 P39 R0
G1 E.8 F1800
G1 F3000
M73 P40 R0
G1 X132.8 Y125.3 E.82674
; stop printing object Cube id:1 copy 0
G1 E-.8 F1800
M73 P41 R0
EXCLUDE_OBJECT_END NAME=Cube_id_1_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode
DISABLE_BOX_HEATER
M141 S0
M140 S0
DISABLE_ALL_SENSOR
G1 E-3 F1800
G0 Z3.2 F600
M73 P42 R0
UNLOAD_FILAMENT T=0
G0 Y270 F12000
M73 P43 R0
G0 X90 Y270 F12000
M73 P47 R0
G1 Z140 F600
M73 P49 R0
M104 S0
M106 P3 S255
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 30.33, 0.00, 0.00, 0.00, 0.00, 0.00
; filament used [cm3] = 0.07, 0.00, 0.00, 0.00, 0.00, 0.00
; filament used [g] = 0.07, 0.00, 0.00, 0.00, 0.00, 0.00
; filament cost = 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
; total filament used [g] = 0.07
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 27s
; estimated first layer printing time (normal mode) = 5s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 1,1,0,0,0,0
; activate_chamber_temp_control = 0,0,0,0,0,0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0,0,0,0,0,0
; adaptive_pressure_advance_bridges = 0,0,0,0,0,0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0";"0,0,0\n0,0,0";"0,0,0\n0,0,0";"0,0,0\n0,0,0";"0,0,0\n0,0,0";"0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0,0,0,0,0,0
; additional_cooling_fan_speed = 10,10,0,70,70,70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0,11x0,11x16,0x16
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 5
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 10
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 1
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 60,60,0,0,0,0
; change_extrusion_role_gcode = 
; change_filament_gcode = PAUSE Z=1\n\n\n\n
; close_fan_the_first_x_layers = 3,3,3,1,1,1
; complete_print_exhaust_fan_speed = 100,100,70,70,70,70
; cool_plate_temp = 0,0,0,35,35,35
; cool_plate_temp_initial_layer = 0,0,0,35,35,35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 10000
; default_bed_type = 
; default_filament_colour = ;;;;;
; default_filament_profile = "Generic PLA @System"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = accel_to_decel_enable;bottom_shell_layers;bridge_flow;bridge_speed;brim_type;brim_width;default_acceleration;elefant_foot_compensation;filter_out_gap_fill;gap_infill_speed;infill_wall_overlap;initial_layer_line_width;inner_wall_line_width;inner_wall_speed;internal_bridge_speed;internal_solid_infill_line_width;internal_solid_infill_speed;line_width;outer_wall_line_width;outer_wall_speed;precise_outer_wall;seam_slope_conditional;seam_slope_inner_walls;skirt_distance;skirt_height;skirt_loops;slow_down_layers;small_area_infill_flow_compensation;small_perimeter_speed;small_perimeter_threshold;sparse_infill_density;sparse_infill_line_width;sparse_infill_pattern;sparse_infill_speed;support_line_width;thick_bridges;top_bottom_infill_wall_overlap;top_shell_layers;top_shell_thickness;top_surface_line_width;top_surface_speed;travel_acceleration;travel_speed;activate_air_filtration;additional_cooling_fan_speed;chamber_temperature;compatible_printers;complete_print_exhaust_fan_speed;during_print_exhaust_fan_speed;enable_pressure_advance;filament_flow_ratio;filament_max_volumetric_speed;filament_retract_when_changing_layer;filament_wipe;pressure_advance;activate_air_filtration;additional_cooling_fan_speed;chamber_temperature;compatible_printers;complete_print_exhaust_fan_speed;during_print_exhaust_fan_speed;enable_pressure_advance;filament_flow_ratio;filament_max_volumetric_speed;filament_retract_when_changing_layer;filament_wipe;pressure_advance;;;;;auxiliary_fan;bed_exclude_area;change_filament_gcode;extruder_clearance_height_to_lid;extruder_clearance_height_to_rod;extruder_clearance_radius;fan_kickstart;fan_speedup_time;layer_change_gcode;machine_end_gcode;machine_max_jerk_e;machine_max_jerk_z;machine_max_speed_e;machine_max_speed_x;machine_max_speed_y;machine_max_speed_z;machine_pause_gcode;machine_start_gcode;nozzle_diameter;print_host;printable_area;printable_height;purge_in_prime_tower;retract_lift_enforce;thumbnails;z_hop_types
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0,0,0,0,0,0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 100,100,70,70,70,70
; elefant_foot_compensation = 0.15
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1,1,1,1,1,1
; enable_overhang_speed = 1
; enable_pressure_advance = 1,1,0,0,0,0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 100,100,100,0,0,0
; eng_plate_temp_initial_layer = 100,100,100,0,0,0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 120
; extruder_clearance_height_to_rod = 40
; extruder_clearance_radius = 70
; extruder_colour = #008000;#808080;#000000;#FF80C0;#FFFFFF;#000000
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 35,35,35,100,100,100
; fan_kickstart = 0.2
; fan_max_speed = 80,80,80,100,100,100
; fan_min_speed = 10,10,10,100,100,100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0.2
; filament_colour = #008000;#808080;#000000;#FF80C0;#FFFFFF;#000000
; filament_cooling_final_speed = 3.4,3.4,3.4,3.4,3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2,2.2,2.2,2.2,2.2
; filament_cooling_moves = 4,4,4,4,4,4
; filament_cost = 23.6,23.6,23.6,20,20,20
; filament_density = 1.02,1.02,1.02,1.24,1.24,1.24
; filament_diameter = 1.75,1.75,1.75,1.75,1.75,1.75
; filament_end_gcode = "; filament end gcode\n";"; filament end gcode\n";"; filament end gcode\n";"; filament end gcode\n";"; filament end gcode\n";"; filament end gcode\n"
; filament_flow_ratio = 0.92,0.92,0.95,0.98,0.98,0.98
; filament_ids = OGFB61;OGFB61;OGFB61;OGFL99;OGFL99;OGFL99
; filament_is_support = 0,0,0,0,0,0
; filament_loading_speed = 28,28,28,28,28,28
; filament_loading_speed_start = 3,3,3,3,3,3
; filament_max_volumetric_speed = 22,22,12,12,12,12
; filament_minimal_purge_on_wipe_tower = 15,15,15,15,15,15
; filament_multitool_ramming = 0,0,0,0,0,0
; filament_multitool_ramming_flow = 10,10,10,10,10,10
; filament_multitool_ramming_volume = 10,10,10,10,10,10
; filament_notes = ;;;;;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_when_changing_layer = 0,0,nil,nil,nil,nil
; filament_settings_id = "0.6 PolyLite ASA @System - Copy";"0.6 PolyLite ASA @System - Copy";"PolyLite ASA @System";"Generic PLA @System";"Generic PLA @System";"Generic PLA @System"
; filament_shrink = 100%,100%,100%,100%,100%,100%
; filament_shrinkage_compensation_z = 100%,100%,100%,100%,100%,100%
; filament_soluble = 0,0,0,0,0,0
; filament_stamping_distance = 0,0,0,0,0,0
; filament_stamping_loading_speed = 0,0,0,0,0,0
; filament_start_gcode = "; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n";"; Filament gcode\n"
; filament_toolchange_delay = 0,0,0,0,0,0
; filament_type = ASA;ASA;ASA;PLA;PLA;PLA
; filament_unloading_speed = 90,90,90,90,90,90
; filament_unloading_speed_start = 100,100,100,100,100,100
; filament_vendor = Polymaker;Polymaker;Polymaker;Generic;Generic;Generic
; filament_wipe = 0,0,nil,nil,nil,nil
; filename_format = {input_filename_base}_{layer_height}mm_{filament_type[initial_tool]}_{printer_model}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 3
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0,262,60,441,505,60,124,0,60,244,343,60,313,345,0,494,560,60,170,122,113,0,323.333,113,151,60,80,126.667,0,80,313,345,60,494,560,0
; flush_volumes_vector = 140,140,140,140,140,140,140,140,140,140,140,140
; full_fan_speed_layer = 0,0,0,0,0,0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 100,100,100,55,55,55
; hot_plate_temp_initial_layer = 100,100,100,55,55,55
; idle_temperature = 0,0,0,0,0,0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = "0.20mm Standard @MyKlipper";"PolyLite ASA @System";"PolyLite ASA @System";;;;;"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.62
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.62
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1,-1,-1,-1,-1,-1
; internal_bridge_flow = 1
; internal_bridge_speed = 100
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.62
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = -1
; ironing_fan_speed = -1,-1,-1,-1,-1,-1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = {if timelapse_type == 1} ; timelapse with wipe tower\nG92 E0\nG1 E-[retraction_length] F1800\nG2 Z{layer_z + 0.4} I0.86 J0.86 P1 F20000 ; spiral lift a little\nG1 Y235 F20000\nG1 X97 F20000\n{if layer_z <=25}\nG1 Z25\n{endif}\nG1 Y254 F2000\nG92 E0\nM400\nTIMELAPSE_TAKE_FRAME\nG1 E[retraction_length] F300\nG1 X85 F2000\nG1 X97 F2000\nG1 Y220 F2000\n{if layer_z <=25}\nG1 Z[layer_z]\n{endif}\n{elsif timelapse_type == 0} ; timelapse without wipe tower\nTIMELAPSE_TAKE_FRAME\n{endif}\nG92 E0\nSET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}
; layer_height = 0.2
; line_width = 0.62
; long_retractions_when_cut = 0
; machine_end_gcode = DISABLE_BOX_HEATER\nM141 S0\nM140 S0\nDISABLE_ALL_SENSOR\nG1 E-3 F1800\nG0 Z{max_layer_z + 3} F600\nUNLOAD_FILAMENT T=[current_extruder]\nG0 Y270 F12000\nG0 X90 Y270 F12000\n{if max_layer_z < max_print_height / 2}G1 Z{max_print_height / 2 + 10} F600{else}G1 Z{min(max_print_height, max_layer_z + 3)}{endif}\nM104 S0
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 4,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 4,0.4
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 30,25
; machine_max_speed_x = 600,200
; machine_max_speed_y = 600,200
; machine_max_speed_z = 20,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M0
; machine_start_gcode = PRINT_START BED=[bed_temperature_initial_layer] HOTEND=[nozzle_temperature_initial_layer] CHAMBER=[overall_chamber_temperature] EXTRUDER=[initial_extruder]\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\nM83\nM140 S[bed_temperature_initial_layer]\nM104 S[nozzle_temperature_initial_layer]\nM141 S[overall_chamber_temperature]\nG4 P3000\nT[initial_tool]\nG1 X108.000 Y1 F30000\nG0 Z[initial_layer_print_height] F600\n;G1 E3 F1800\nG90\nM83\nG0 X128 E8  F{outer_wall_volumetric_speed/(24/20)    * 60}\nG0 X133 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG0 X138 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\nG0 X143 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG0 X148 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\nG0 X153 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG91\nG1 X1 Z-0.300\nG1 X4\nG1 Z1 F1200\nG90\nM400\nG1 X108.000 Y2.5 F30000\nG0 Z[initial_layer_print_height] F600\nM83\nG0 X128 E10  F{outer_wall_volumetric_speed/(24/20)    * 60}\nG0 X133 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG0 X138 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\nG0 X143 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG0 X148 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)     * 60}\nG0 X153 E.3742  F{outer_wall_volumetric_speed/(0.3*0.5)/4     * 60}\nG91\nG1 X1 Z-0.300\nG1 X4\nG1 Z1 F1200\nG90\nM400\nG1 Z1 F600
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 4
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.6
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 260,260,260,220,220,220
; nozzle_temperature_initial_layer = 260,260,260,220,220,220
; nozzle_temperature_range_high = 280,280,280,240,240,240
; nozzle_temperature_range_low = 240,240,240,190,190,190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 3000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.62
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 80,80,80,100,100,100
; overhang_fan_threshold = 25%,25%,25%,50%,50%,50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157,0.4157,0.4157,0.4157,0.4157,0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.015,0.015,0.02,0.02,0.02,0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle";"MyKlipper 0.6 nozzle";"MyKlipper 0.8 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Q2 0.6nozzle
; printable_area = 0x0,270x0,270x270,0x270
; printable_height = 260
; printer_model = Generic Klipper Printer
; printer_notes = 
; printer_settings_id = Q2 .6
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1,1,1,1,1,1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3,3,3,3,3,3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = Top and Bottom
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 1
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 1
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 4
; skirt_height = 1
; skirt_loops = 1
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1,1,1,1,1,1
; slow_down_layer_time = 3,3,3,4,4,4
; slow_down_layers = 1
; slow_down_min_speed = 10,10,10,10,10,10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 1
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 20
; small_perimeter_threshold = 4
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 10%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.62
; sparse_infill_pattern = honeycomb
; sparse_infill_rotate_template = 
; sparse_infill_speed = 270
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 0,0,0,45,45,45
; supertack_plate_temp_initial_layer = 0,0,0,45,45,45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.62
; support_material_interface_fan_speed = -1,-1,-1,-1,-1,-1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 110,110,110,45,45,45
; template_custom_gcode = 
; textured_cool_plate_temp = 40,40,40,40,40,40
; textured_cool_plate_temp_initial_layer = 40,40,40,40,40,40
; textured_plate_temp = 100,100,100,55,55,55
; textured_plate_temp_initial_layer = 100,100,100,55,55,55
; thick_bridges = 1
; thick_internal_bridges = 1
; thumbnails = 50x50/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 30%
; top_shell_layers = 5
; top_shell_thickness = 0
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 3000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0.62
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 30
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Slope Lift
; z_offset = 0
; first_layer_bed_temperature = 100
; bed_shape = 0x0,270x0,270x270,0x270
; first_layer_temperature = 260
; first_layer_height = 0.200
; CONFIG_BLOCK_END


